"""reservation updates

Revision ID: 01f50c3d378b
Revises: ee13ff07d12c
Create Date: 2026-08-11 10:10:31.092843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f50c3d378b'
down_revision: Union[str, Sequence[str], None] = 'ee13ff07d12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_updates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('route_change', 'preparation', 'payment', 'departure_logistics', 'incident', 'general', name='update_category', schema='yatra', inherit_schema=True), server_default=sa.text("'general'"), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('published_by', sa.String(length=120), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(trim(body)) > 0', name=op.f('ck_reservation_updates_update_body_present')),
    sa.CheckConstraint('length(trim(published_by)) > 0', name=op.f('ck_reservation_updates_update_author_present')),
    sa.CheckConstraint('length(trim(title)) > 0', name=op.f('ck_reservation_updates_update_title_present')),
    sa.ForeignKeyConstraint(['reservation_id'], ['yatra.reservations.id'], name=op.f('fk_reservation_updates_reservation_id_reservations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation_updates')),
    schema='yatra'
    )
    op.create_index('ix_reservation_updates_reservation', 'reservation_updates', ['reservation_id', 'created_at'], unique=False, schema='yatra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reservation_updates_reservation', table_name='reservation_updates', schema='yatra')
    op.drop_table('reservation_updates', schema='yatra')
    # ### end Alembic commands ###
