"""route status subscriptions and outbound queue

Revision ID: 0c5ce0bcbb67
Revises: 35bf50ff102a
Create Date: 2026-08-12 14:44:00.889139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0c5ce0bcbb67'
down_revision: Union[str, Sequence[str], None] = '35bf50ff102a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'email', 'sms', name='subscription_channel', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('destination', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('route_segment_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('pending', 'active', 'unsubscribed', 'suppressed', name='subscription_state', schema='yatra', inherit_schema=True), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('source_page', sa.String(length=200), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('confirm_token', sa.String(length=64), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suppressed_reason', sa.Text(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("state <> 'active' or confirmed_at is not null", name=op.f('ck_status_subscriptions_active_subscription_needs_confirmation')),
    sa.CheckConstraint('length(trim(destination)) > 0', name=op.f('ck_status_subscriptions_destination_present')),
    sa.ForeignKeyConstraint(['lead_id'], ['yatra.leads.id'], name=op.f('fk_status_subscriptions_lead_id_leads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_segment_id'], ['yatra.route_segments.id'], name=op.f('fk_status_subscriptions_route_segment_id_route_segments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_subscriptions')),
    sa.UniqueConstraint('channel', 'destination', 'route_segment_id', name='one_subscription_each'),
    sa.UniqueConstraint('confirm_token', name=op.f('uq_status_subscriptions_confirm_token')),
    sa.UniqueConstraint('unsubscribe_token', name=op.f('uq_status_subscriptions_unsubscribe_token')),
    schema='yatra'
    )
    op.create_index('ix_status_subscriptions_segment', 'status_subscriptions', ['route_segment_id'], unique=False, schema='yatra')
    op.create_index('ix_status_subscriptions_state', 'status_subscriptions', ['state'], unique=False, schema='yatra')
    op.create_table('outbound_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('status_update_id', sa.Integer(), nullable=True),
    # Second use of `subscription_channel`: status_subscriptions above already
    # created the type. Autogenerate emits CREATE TYPE for both and the migration
    # fails with DuplicateObject. Any table reusing an enum needs create_type=False.
    sa.Column('channel', postgresql.ENUM(name='subscription_channel', schema='yatra', create_type=False), nullable=False),
    sa.Column('destination', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=20), server_default=sa.text("'notable'"), nullable=False),
    sa.Column('send_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.Enum('queued', 'sent', 'failed', 'suppressed', name='outbound_state', schema='yatra', inherit_schema=True), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('suppressed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("state <> 'suppressed' or length(trim(coalesce(suppressed_reason,''))) > 0", name=op.f('ck_outbound_messages_suppression_needs_a_reason')),
    sa.CheckConstraint('length(trim(body)) > 0', name=op.f('ck_outbound_messages_outbound_body_present')),
    sa.CheckConstraint('length(trim(subject)) > 0', name=op.f('ck_outbound_messages_outbound_subject_present')),
    sa.ForeignKeyConstraint(['status_update_id'], ['yatra.status_updates.id'], name=op.f('fk_outbound_messages_status_update_id_status_updates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['yatra.status_subscriptions.id'], name=op.f('fk_outbound_messages_subscription_id_status_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbound_messages')),
    sa.UniqueConstraint('subscription_id', 'status_update_id', name='one_message_per_update'),
    schema='yatra'
    )
    op.create_index('ix_outbound_due', 'outbound_messages', ['state', 'send_after'], unique=False, schema='yatra')
    op.create_index('ix_outbound_subscription', 'outbound_messages', ['subscription_id', 'created_at'], unique=False, schema='yatra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbound_subscription', table_name='outbound_messages', schema='yatra')
    op.drop_index('ix_outbound_due', table_name='outbound_messages', schema='yatra')
    op.drop_table('outbound_messages', schema='yatra')
    op.drop_index('ix_status_subscriptions_state', table_name='status_subscriptions', schema='yatra')
    op.drop_index('ix_status_subscriptions_segment', table_name='status_subscriptions', schema='yatra')
    op.drop_table('status_subscriptions', schema='yatra')
    # ### end Alembic commands ###
