"""partner access tokens

Revision ID: 0f647b3d522f
Revises: 892a63556ea2
Create Date: 2026-08-14 09:31:48.051724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f647b3d522f'
down_revision: Union[str, Sequence[str], None] = '892a63556ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_access_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operating_partner_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('issued_by', sa.String(length=120), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('use_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(trim(label)) > 0', name=op.f('ck_partner_access_tokens_partner_token_label_present')),
    sa.CheckConstraint('revoked_at is null or revoked_reason is not null', name=op.f('ck_partner_access_tokens_partner_revocation_needs_a_reason')),
    sa.ForeignKeyConstraint(['operating_partner_id'], ['yatra.operating_partners.id'], name=op.f('fk_partner_access_tokens_operating_partner_id_operating_partners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_access_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_partner_access_tokens_token_hash')),
    schema='yatra'
    )
    op.create_index('ix_partner_tokens_partner', 'partner_access_tokens', ['operating_partner_id'], unique=False, schema='yatra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_partner_tokens_partner', table_name='partner_access_tokens', schema='yatra')
    op.drop_table('partner_access_tokens', schema='yatra')
    # ### end Alembic commands ###
