"""altitude verification flag

Revision ID: 2732abf60136
Revises: d03cf559ea26
Create Date: 2026-08-13 20:20:41.190810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2732abf60136'
down_revision: Union[str, Sequence[str], None] = 'd03cf559ea26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('altitude_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='yatra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'altitude_verified', schema='yatra')
    # ### end Alembic commands ###
