"""content hub articles and faqs

Revision ID: 35bf50ff102a
Revises: fa0ff3a1785b
Create Date: 2026-08-12 14:33:59.700282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35bf50ff102a'
down_revision: Union[str, Sequence[str], None] = 'fa0ff3a1785b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('cluster', sa.Enum('route_and_status', 'preparation', 'cost_and_tiers', 'accommodation', 'gateway_and_transport', 'health_and_altitude', 'culture_and_tradition', 'field_report', name='article_cluster', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('state', sa.Enum('draft', 'in_review', 'published', 'retired', name='article_state', schema='yatra', inherit_schema=True), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('title', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_interval_days', sa.Integer(), server_default=sa.text('180'), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=True),
    sa.Column('is_pillar', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("answer IS NULL OR (jsonb_exists(answer, 'en') AND length(trim(answer ->> 'en')) > 0)", name=op.f('ck_articles_answer_has_english')),
    sa.CheckConstraint("state <> 'published' or (length(trim(coalesce(author, ''))) > 0 and length(trim(coalesce(reviewed_by, ''))) > 0 and last_reviewed_at is not null)", name=op.f('ck_articles_published_article_needs_named_review')),
    sa.CheckConstraint("title IS NULL OR (jsonb_exists(title, 'en') AND length(trim(title ->> 'en')) > 0)", name=op.f('ck_articles_title_has_english')),
    sa.CheckConstraint('review_interval_days > 0', name=op.f('ck_articles_review_interval_is_positive')),
    sa.ForeignKeyConstraint(['journey_id'], ['yatra.journeys.id'], name=op.f('fk_articles_journey_id_journeys'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['yatra.articles.id'], name=op.f('fk_articles_parent_id_articles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('slug', name='uq_articles_slug'),
    schema='yatra'
    )
    op.create_index('ix_articles_cluster_state', 'articles', ['cluster', 'state'], unique=False, schema='yatra')
    op.create_table('article_faqs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('question', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('asked_by_traveller', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("answer IS NULL OR (jsonb_exists(answer, 'en') AND length(trim(answer ->> 'en')) > 0)", name=op.f('ck_article_faqs_answer_has_english')),
    sa.CheckConstraint("question IS NULL OR (jsonb_exists(question, 'en') AND length(trim(question ->> 'en')) > 0)", name=op.f('ck_article_faqs_question_has_english')),
    sa.ForeignKeyConstraint(['article_id'], ['yatra.articles.id'], name=op.f('fk_article_faqs_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_faqs')),
    schema='yatra'
    )
    op.create_index('ix_article_faqs_article', 'article_faqs', ['article_id', 'sort_order'], unique=False, schema='yatra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_article_faqs_article', table_name='article_faqs', schema='yatra')
    op.drop_table('article_faqs', schema='yatra')
    op.drop_index('ix_articles_cluster_state', table_name='articles', schema='yatra')
    op.drop_table('articles', schema='yatra')
    # ### end Alembic commands ###
