"""staff auth, documents, weather

Revision ID: 3fcf1de0afaa
Revises: c5ab18b9c601
Create Date: 2026-08-08 23:52:12.081186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fcf1de0afaa'
down_revision: Union[str, Sequence[str], None] = 'c5ab18b9c601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=40)), server_default=sa.text("'{read_only}'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('array_length(roles, 1) >= 1', name=op.f('ck_staff_users_staff_needs_a_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_users')),
    schema='yatra'
    )
    op.create_index('ix_staff_users_email', 'staff_users', ['email'], unique=True, schema='yatra')
    op.create_table('staff_verifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('identifier', sa.String(length=320), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_verifications')),
    schema='yatra'
    )
    op.create_table('staff_accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('id_token', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['yatra.staff_users.id'], name=op.f('fk_staff_accounts_user_id_staff_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_accounts')),
    schema='yatra'
    )
    op.create_table('staff_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['yatra.staff_users.id'], name=op.f('fk_staff_sessions_user_id_staff_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_sessions')),
    schema='yatra'
    )
    op.create_index('ix_staff_sessions_token', 'staff_sessions', ['token'], unique=True, schema='yatra')
    op.create_table('weather_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('route_segment_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.Enum('clear', 'partly_cloudy', 'overcast', 'rain', 'heavy_rain', 'snow', 'heavy_snow', 'fog', 'storm', 'unknown', name='weather_condition', schema='yatra', inherit_schema=True), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('temp_min_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('temp_max_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('wind_kph', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('snow_depth_cm', sa.Integer(), nullable=True),
    sa.Column('advisory', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.Enum('field_coordinator', 'operating_partner', 'official_forecast', 'weather_api', name='weather_source', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('is_field_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('observed_by', sa.String(length=120), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_update_due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('destination_id is not null or route_segment_id is not null', name=op.f('ck_weather_snapshots_weather_needs_a_place')),
    sa.CheckConstraint('next_update_due > observed_at', name=op.f('ck_weather_snapshots_update_window_forward')),
    sa.CheckConstraint('not is_field_verified or observed_by is not null', name=op.f('ck_weather_snapshots_field_verification_needs_an_observer')),
    sa.CheckConstraint('temp_min_c is null or temp_max_c is null or temp_max_c >= temp_min_c', name=op.f('ck_weather_snapshots_temperature_range_ordered')),
    sa.ForeignKeyConstraint(['destination_id'], ['yatra.destinations.id'], name=op.f('fk_weather_snapshots_destination_id_destinations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_segment_id'], ['yatra.route_segments.id'], name=op.f('fk_weather_snapshots_route_segment_id_route_segments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_snapshots')),
    schema='yatra'
    )
    op.create_index('ix_weather_destination_observed', 'weather_snapshots', ['destination_id', 'observed_at'], unique=False, schema='yatra')
    op.create_index('ix_weather_segment_observed', 'weather_snapshots', ['route_segment_id', 'observed_at'], unique=False, schema='yatra')
    op.create_table('document_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('label', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('journey_id', sa.Integer(), nullable=True),
    sa.Column('departure_id', sa.Integer(), nullable=True),
    sa.Column('applies_to', sa.Enum('all', 'indian_national', 'foreign_national', 'minor', name='traveller_category', schema='yatra', inherit_schema=True), server_default=sa.text("'all'"), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_permit_bearing', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('guarantees_nothing', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('requires_file', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("label IS NULL OR (jsonb_exists(label, 'en') AND length(trim(label ->> 'en')) > 0)", name=op.f('ck_document_requirements_label_has_english')),
    sa.CheckConstraint('not (is_mandatory and is_permit_bearing and guarantees_nothing = false)', name=op.f('ck_document_requirements_permit_documents_cannot_promise_approval')),
    sa.ForeignKeyConstraint(['departure_id'], ['yatra.departures.id'], name=op.f('fk_document_requirements_departure_id_departures'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journey_id'], ['yatra.journeys.id'], name=op.f('fk_document_requirements_journey_id_journeys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_requirements')),
    sa.UniqueConstraint('code', 'journey_id', 'departure_id', 'applies_to', name=op.f('uq_document_requirements_code')),
    schema='yatra'
    )
    op.create_index('ix_document_requirements_journey', 'document_requirements', ['journey_id'], unique=False, schema='yatra')
    op.create_table('document_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('departure_id', sa.Integer(), nullable=True),
    sa.Column('traveller_name', sa.String(length=200), nullable=True),
    sa.Column('state', sa.Enum('required', 'awaiting_upload', 'uploaded', 'under_review', 'accepted', 'needs_correction', 'expired', 'waived', 'submitted_to_operator', 'outcome_recorded', name='document_state', schema='yatra', inherit_schema=True), server_default=sa.text("'required'"), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correction_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('waived_by', sa.String(length=120), nullable=True),
    sa.Column('waiver_reason', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('operator_outcome', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("state <> 'accepted' or reviewed_by is not null", name=op.f('ck_document_submissions_acceptance_requires_a_reviewer')),
    sa.CheckConstraint("state <> 'needs_correction' or correction_reason is not null", name=op.f('ck_document_submissions_correction_requires_a_reason')),
    sa.CheckConstraint("state <> 'waived' or (waived_by is not null and waiver_reason is not null)", name=op.f('ck_document_submissions_waiver_requires_owner_and_reason')),
    sa.CheckConstraint("state in ('required','awaiting_upload','waived') or storage_key is not null", name=op.f('ck_document_submissions_submitted_document_needs_storage_key')),
    sa.ForeignKeyConstraint(['departure_id'], ['yatra.departures.id'], name=op.f('fk_document_submissions_departure_id_departures'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['yatra.leads.id'], name=op.f('fk_document_submissions_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['yatra.document_requirements.id'], name=op.f('fk_document_submissions_requirement_id_document_requirements'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_submissions')),
    schema='yatra'
    )
    op.create_index('ix_document_submissions_lead', 'document_submissions', ['lead_id'], unique=False, schema='yatra')
    op.create_index('ix_document_submissions_state', 'document_submissions', ['state'], unique=False, schema='yatra')
    op.create_table('document_access_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('staff_user_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['yatra.document_submissions.id'], name=op.f('fk_document_access_log_submission_id_document_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_access_log')),
    schema='yatra'
    )
    op.create_index('ix_document_access_log_submission', 'document_access_log', ['submission_id', 'created_at'], unique=False, schema='yatra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_access_log_submission', table_name='document_access_log', schema='yatra')
    op.drop_table('document_access_log', schema='yatra')
    op.drop_index('ix_document_submissions_state', table_name='document_submissions', schema='yatra')
    op.drop_index('ix_document_submissions_lead', table_name='document_submissions', schema='yatra')
    op.drop_table('document_submissions', schema='yatra')
    op.drop_index('ix_document_requirements_journey', table_name='document_requirements', schema='yatra')
    op.drop_table('document_requirements', schema='yatra')
    op.drop_index('ix_weather_segment_observed', table_name='weather_snapshots', schema='yatra')
    op.drop_index('ix_weather_destination_observed', table_name='weather_snapshots', schema='yatra')
    op.drop_table('weather_snapshots', schema='yatra')
    op.drop_index('ix_staff_sessions_token', table_name='staff_sessions', schema='yatra')
    op.drop_table('staff_sessions', schema='yatra')
    op.drop_table('staff_accounts', schema='yatra')
    op.drop_table('staff_verifications', schema='yatra')
    op.drop_index('ix_staff_users_email', table_name='staff_users', schema='yatra')
    op.drop_table('staff_users', schema='yatra')
    # ### end Alembic commands ###

    for enum_name in (
        "staff_role", "document_state", "traveller_category",
        "weather_condition", "weather_source",
    ):
        op.execute(f'DROP TYPE IF EXISTS yatra."{enum_name}"')
