"""shorten permit constraint name

Revision ID: 602d501a15fe
Revises: 3fcf1de0afaa
Create Date: 2026-08-08 23:53:00.765550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602d501a15fe'
down_revision: Union[str, Sequence[str], None] = '3fcf1de0afaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_document_requirements_permit_documents_cannot_promis_6d41'), 'document_requirements', schema='yatra', type_='check')
    op.create_check_constraint(op.f('ck_document_requirements_permit_docs_cannot_promise_approval'), 'document_requirements', 'not (is_mandatory and is_permit_bearing and guarantees_nothing = false)', schema='yatra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_document_requirements_permit_docs_cannot_promise_approval'), 'document_requirements', schema='yatra', type_='check')
    op.create_check_constraint(op.f('ck_document_requirements_permit_documents_cannot_promis_6d41'), 'document_requirements', 'NOT (is_mandatory AND is_permit_bearing AND guarantees_nothing = false)', schema='yatra')
    # ### end Alembic commands ###
