"""reservations, party, policy acceptance and payment ledger

Revision ID: 62a3cc051248
Revises: a8c4c15e2ebb
Create Date: 2026-08-10 22:18:07.295349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a3cc051248'
down_revision: Union[str, Sequence[str], None] = 'a8c4c15e2ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('departure_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('draft', 'proposed', 'held', 'confirmed', 'preparing', 'ready', 'travelled', 'cancelled_by_traveller', 'cancelled_by_us', 'lapsed', name='reservation_state', schema='yatra', inherit_schema=True), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('agreed_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('coordinator_staff_id', sa.String(length=64), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('next_action_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state_changed_by', sa.String(length=120), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("state not in ('cancelled_by_traveller','cancelled_by_us') or length(trim(coalesce(cancellation_reason, ''))) > 0", name=op.f('ck_reservations_cancellation_needs_reason')),
    sa.CheckConstraint("state not in ('confirmed','preparing','ready','travelled') or coordinator_staff_id is not null", name=op.f('ck_reservations_confirmed_reservation_needs_coordinator')),
    sa.CheckConstraint('agreed_amount >= 0', name=op.f('ck_reservations_agreed_amount_non_negative')),
    sa.CheckConstraint('party_size >= 1', name=op.f('ck_reservations_party_size_at_least_one')),
    sa.ForeignKeyConstraint(['coordinator_staff_id'], ['yatra.staff_users.id'], name=op.f('fk_reservations_coordinator_staff_id_staff_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['departure_id'], ['yatra.departures.id'], name=op.f('fk_reservations_departure_id_departures'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['yatra.leads.id'], name=op.f('fk_reservations_lead_id_leads'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations')),
    sa.UniqueConstraint('reference', name=op.f('uq_reservations_reference')),
    schema='yatra'
    )
    op.create_index('ix_reservations_coordinator', 'reservations', ['coordinator_staff_id'], unique=False, schema='yatra')
    op.create_index('ix_reservations_departure_state', 'reservations', ['departure_id', 'state'], unique=False, schema='yatra')
    op.create_table('payment_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('received', 'refunded', name='payment_direction', schema='yatra', inherit_schema=True), server_default=sa.text("'received'"), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('method', sa.Enum('bank_transfer', 'upi', 'cash', 'cheque', 'gateway', name='payment_method', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payment_records_amount_positive')),
    sa.CheckConstraint('length(trim(recorded_by)) > 0', name=op.f('ck_payment_records_recorder_present')),
    sa.ForeignKeyConstraint(['reservation_id'], ['yatra.reservations.id'], name=op.f('fk_payment_records_reservation_id_reservations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_records')),
    schema='yatra'
    )
    op.create_index('ix_payment_records_reservation', 'payment_records', ['reservation_id', 'received_at'], unique=False, schema='yatra')
    op.create_table('policy_acceptances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('policy', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('accepted_by', sa.String(length=200), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel', sa.String(length=40), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('recorded_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(trim(accepted_by)) > 0', name=op.f('ck_policy_acceptances_acceptor_present')),
    sa.ForeignKeyConstraint(['reservation_id'], ['yatra.reservations.id'], name=op.f('fk_policy_acceptances_reservation_id_reservations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_acceptances')),
    sa.UniqueConstraint('reservation_id', 'policy', 'version', name='one_acceptance_per_version'),
    schema='yatra'
    )
    op.create_index('ix_policy_acceptances_reservation', 'policy_acceptances', ['reservation_id'], unique=False, schema='yatra')
    op.create_table('reservation_travellers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('group_lead', 'companion', name='traveller_role', schema='yatra', inherit_schema=True), server_default=sa.text("'companion'"), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('relationship_to_lead', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('is_senior', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_disclosed_health_information', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('dietary_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(trim(full_name)) > 0', name=op.f('ck_reservation_travellers_traveller_name_present')),
    sa.ForeignKeyConstraint(['reservation_id'], ['yatra.reservations.id'], name=op.f('fk_reservation_travellers_reservation_id_reservations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation_travellers')),
    schema='yatra'
    )
    op.create_index('ix_reservation_travellers_reservation', 'reservation_travellers', ['reservation_id'], unique=False, schema='yatra')
    op.create_index('uq_reservation_one_group_lead', 'reservation_travellers', ['reservation_id'], unique=True, schema='yatra', postgresql_where=sa.text("role = 'group_lead'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_reservation_one_group_lead', table_name='reservation_travellers', schema='yatra', postgresql_where=sa.text("role = 'group_lead'"))
    op.drop_index('ix_reservation_travellers_reservation', table_name='reservation_travellers', schema='yatra')
    op.drop_table('reservation_travellers', schema='yatra')
    op.drop_index('ix_policy_acceptances_reservation', table_name='policy_acceptances', schema='yatra')
    op.drop_table('policy_acceptances', schema='yatra')
    op.drop_index('ix_payment_records_reservation', table_name='payment_records', schema='yatra')
    op.drop_table('payment_records', schema='yatra')
    op.drop_index('ix_reservations_departure_state', table_name='reservations', schema='yatra')
    op.drop_index('ix_reservations_coordinator', table_name='reservations', schema='yatra')
    op.drop_table('reservations', schema='yatra')
    # ### end Alembic commands ###
