"""acquisition spend

Revision ID: 73b64a025815
Revises: 8c809c23bfac
Create Date: 2026-08-13 12:07:07.465188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b64a025815'
down_revision: Union[str, Sequence[str], None] = '8c809c23bfac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisition_spend',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=120), nullable=False),
    sa.Column('campaign', sa.String(length=160), server_default=sa.text("''"), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_acquisition_spend_spend_not_negative')),
    sa.CheckConstraint('length(trim(channel)) > 0', name=op.f('ck_acquisition_spend_spend_channel_present')),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_acquisition_spend_spend_period_ordered')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acquisition_spend')),
    sa.UniqueConstraint('channel', 'campaign', 'period_start', name='one_spend_row_per_period'),
    schema='yatra'
    )
    op.create_index('ix_acquisition_spend_period', 'acquisition_spend', ['period_start', 'period_end'], unique=False, schema='yatra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_acquisition_spend_period', table_name='acquisition_spend', schema='yatra')
    op.drop_table('acquisition_spend', schema='yatra')
    # ### end Alembic commands ###
