"""link document submissions to reservations and travellers

Revision ID: 87e61cf3e55c
Revises: 62a3cc051248
Create Date: 2026-08-10 22:21:06.972200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e61cf3e55c'
down_revision: Union[str, Sequence[str], None] = '62a3cc051248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_submissions', sa.Column('reservation_id', sa.Integer(), nullable=True), schema='yatra')
    op.add_column('document_submissions', sa.Column('reservation_traveller_id', sa.Integer(), nullable=True), schema='yatra')
    # ### end Alembic commands ###

    # Written by hand, because autogenerate did not emit them and the columns are
    # useless without them.
    #
    # The `include_object` filter in alembic/env.py rejects any foreign_key_constraint
    # whose `target_fullname` has two parts ("reservations.id"), since a bare
    # two-part target is how a cross-schema FK into Raahi's `public` would appear.
    # Every model declares FKs exactly that way. Inside `create_table` the FK is
    # emitted inline as part of the table, so the filter is never consulted and the
    # earlier migrations were unaffected. On `add_column` it needs a separate
    # `create_foreign_key`, the filter drops it, and you get columns with no
    # referential integrity and no error. Add FKs explicitly on any add_column.
    op.create_foreign_key(
        op.f("fk_document_submissions_reservation_id_reservations"),
        "document_submissions",
        "reservations",
        ["reservation_id"],
        ["id"],
        source_schema="yatra",
        referent_schema="yatra",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_document_submissions_res_traveller"),
        "document_submissions",
        "reservation_travellers",
        ["reservation_traveller_id"],
        ["id"],
        source_schema="yatra",
        referent_schema="yatra",
        ondelete="CASCADE",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_document_submissions_res_traveller"),
        "document_submissions",
        schema="yatra",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_document_submissions_reservation_id_reservations"),
        "document_submissions",
        schema="yatra",
        type_="foreignkey",
    )
    op.drop_column('document_submissions', 'reservation_traveller_id', schema='yatra')
    op.drop_column('document_submissions', 'reservation_id', schema='yatra')
    # ### end Alembic commands ###
