"""assist query log

Revision ID: 892a63556ea2
Revises: 2732abf60136
Create Date: 2026-08-14 01:26:01.874018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '892a63556ea2'
down_revision: Union[str, Sequence[str], None] = '2732abf60136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assist_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('asked_by', sa.String(length=120), nullable=True),
    sa.Column('locale', sa.String(length=8), server_default=sa.text("'en'"), nullable=False),
    sa.Column('refusal', sa.String(length=40), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('passage_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('quoted_status', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('contract_version', sa.String(length=40), nullable=True),
    sa.Column('was_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(trim(question)) > 0', name=op.f('ck_assist_queries_assist_question_present')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assist_queries')),
    schema='yatra'
    )
    op.create_index('ix_assist_queries_created', 'assist_queries', ['created_at'], unique=False, schema='yatra')
    op.create_index('ix_assist_queries_refusal', 'assist_queries', ['refusal'], unique=False, schema='yatra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assist_queries_refusal', table_name='assist_queries', schema='yatra')
    op.drop_index('ix_assist_queries_created', table_name='assist_queries', schema='yatra')
    op.drop_table('assist_queries', schema='yatra')
    # ### end Alembic commands ###
