"""outbound message templates

Revision ID: 8c809c23bfac
Revises: f62c31b08c3d
Create Date: 2026-08-13 11:36:25.870135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c809c23bfac'
down_revision: Union[str, Sequence[str], None] = 'f62c31b08c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_messages', sa.Column('template_name', sa.String(length=80), nullable=True), schema='yatra')
    op.add_column('outbound_messages', sa.Column('template_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='yatra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbound_messages', 'template_parameters', schema='yatra')
    op.drop_column('outbound_messages', 'template_name', schema='yatra')
    # ### end Alembic commands ###
