"""traveller access tokens

Revision ID: a8c4c15e2ebb
Revises: 602d501a15fe
Create Date: 2026-08-10 01:57:40.328963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c4c15e2ebb'
down_revision: Union[str, Sequence[str], None] = '602d501a15fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traveller_access_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=120), nullable=True),
    sa.Column('issued_by', sa.String(length=120), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('use_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_traveller_access_tokens_expiry_is_forward')),
    sa.ForeignKeyConstraint(['lead_id'], ['yatra.leads.id'], name=op.f('fk_traveller_access_tokens_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traveller_access_tokens')),
    schema='yatra'
    )
    op.create_index('ix_traveller_access_tokens_hash', 'traveller_access_tokens', ['token_hash'], unique=True, schema='yatra')
    op.create_index('ix_traveller_access_tokens_lead', 'traveller_access_tokens', ['lead_id'], unique=False, schema='yatra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_traveller_access_tokens_lead', table_name='traveller_access_tokens', schema='yatra')
    op.drop_index('ix_traveller_access_tokens_hash', table_name='traveller_access_tokens', schema='yatra')
    op.drop_table('traveller_access_tokens', schema='yatra')
    # ### end Alembic commands ###
