"""supplier reviews and manual hold

Revision ID: aef737d73349
Revises: 73b64a025815
Create Date: 2026-08-13 12:25:27.525135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef737d73349'
down_revision: Union[str, Sequence[str], None] = '73b64a025815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('departure_id', sa.Integer(), nullable=False),
    sa.Column('confirmation_reliability', sa.SmallInteger(), nullable=True),
    sa.Column('punctuality', sa.SmallInteger(), nullable=True),
    sa.Column('accuracy_against_promise', sa.SmallInteger(), nullable=True),
    sa.Column('cleanliness_and_condition', sa.SmallInteger(), nullable=True),
    sa.Column('staff_behaviour', sa.SmallInteger(), nullable=True),
    sa.Column('communication', sa.SmallInteger(), nullable=True),
    sa.Column('issue_resolution', sa.SmallInteger(), nullable=True),
    sa.Column('would_use_again', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("would_use_again is not false or length(trim(coalesce(note,''))) > 0", name=op.f('ck_supplier_reviews_refusing_a_vendor_needs_a_reason')),
    sa.CheckConstraint('accuracy_against_promise is null or accuracy_against_promise between 1 and 5', name=op.f('ck_supplier_reviews_accuracy_against_promise_range')),
    sa.CheckConstraint('cleanliness_and_condition is null or cleanliness_and_condition between 1 and 5', name=op.f('ck_supplier_reviews_cleanliness_and_condition_range')),
    sa.CheckConstraint('communication is null or communication between 1 and 5', name=op.f('ck_supplier_reviews_communication_range')),
    sa.CheckConstraint('confirmation_reliability is null or confirmation_reliability between 1 and 5', name=op.f('ck_supplier_reviews_confirmation_reliability_range')),
    sa.CheckConstraint('issue_resolution is null or issue_resolution between 1 and 5', name=op.f('ck_supplier_reviews_issue_resolution_range')),
    sa.CheckConstraint('punctuality is null or punctuality between 1 and 5', name=op.f('ck_supplier_reviews_punctuality_range')),
    sa.CheckConstraint('staff_behaviour is null or staff_behaviour between 1 and 5', name=op.f('ck_supplier_reviews_staff_behaviour_range')),
    sa.ForeignKeyConstraint(['departure_id'], ['yatra.departures.id'], name=op.f('fk_supplier_reviews_departure_id_departures'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['yatra.suppliers.id'], name=op.f('fk_supplier_reviews_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_reviews')),
    sa.UniqueConstraint('supplier_id', 'departure_id', name='one_review_per_supplier_departure'),
    schema='yatra'
    )
    op.create_index('ix_supplier_reviews_supplier', 'supplier_reviews', ['supplier_id'], unique=False, schema='yatra')
    op.add_column('suppliers', sa.Column('hold_reason', sa.Text(), nullable=True), schema='yatra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'hold_reason', schema='yatra')
    op.drop_index('ix_supplier_reviews_supplier', table_name='supplier_reviews', schema='yatra')
    op.drop_table('supplier_reviews', schema='yatra')
    # ### end Alembic commands ###
