"""initial yatra schema

Revision ID: c5ab18b9c601
Revises: 
Create Date: 2026-08-08 21:12:20.161592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5ab18b9c601'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('altitude_m', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("name IS NULL OR (jsonb_exists(name, 'en') AND length(trim(name ->> 'en')) > 0)", name=op.f('ck_destinations_name_has_english')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_destinations')),
    sa.UniqueConstraint('slug', name=op.f('uq_destinations_slug')),
    schema='yatra'
    )
    op.create_table('journeys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('essence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('family', sa.Enum('sacred_flagship', 'kumaon_circuit', 'homestay_immersion', 'paths_of_mahadev', 'private_sacred', 'cultural_experience', 'ground_services', name='journey_family', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('gateway', sa.String(length=120), nullable=True),
    sa.Column('duration_nights', sa.Integer(), nullable=True),
    sa.Column('highest_altitude_m', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_reviewed_at', sa.String(length=32), nullable=True),
    sa.Column('last_reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("name IS NULL OR (jsonb_exists(name, 'en') AND length(trim(name ->> 'en')) > 0)", name=op.f('ck_journeys_name_has_english')),
    sa.CheckConstraint('not is_published or (essence is not null and duration_nights is not null)', name=op.f('ck_journeys_published_journey_needs_facts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journeys')),
    sa.UniqueConstraint('slug', name=op.f('uq_journeys_slug')),
    schema='yatra'
    )
    op.create_table('operating_partners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('public_name', sa.String(length=200), nullable=True),
    sa.Column('registration_number', sa.String(length=120), nullable=True),
    sa.Column('registration_valid_until', sa.Date(), nullable=True),
    sa.Column('is_contracting_entity', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('support_contact', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operating_partners')),
    schema='yatra'
    )
    op.create_table('itinerary_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['yatra.journeys.id'], name=op.f('fk_itinerary_versions_journey_id_journeys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itinerary_versions')),
    sa.UniqueConstraint('journey_id', 'version', name=op.f('uq_itinerary_versions_journey_id')),
    schema='yatra'
    )
    op.create_table('route_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('origin_destination_id', sa.Integer(), nullable=True),
    sa.Column('arrival_destination_id', sa.Integer(), nullable=True),
    sa.Column('requires_permit', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('seasonal_note', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("name IS NULL OR (jsonb_exists(name, 'en') AND length(trim(name ->> 'en')) > 0)", name=op.f('ck_route_segments_name_has_english')),
    sa.ForeignKeyConstraint(['arrival_destination_id'], ['yatra.destinations.id'], name=op.f('fk_route_segments_arrival_destination_id_destinations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_destination_id'], ['yatra.destinations.id'], name=op.f('fk_route_segments_origin_destination_id_destinations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_segments')),
    sa.UniqueConstraint('slug', name=op.f('uq_route_segments_slug')),
    schema='yatra'
    )
    op.create_table('service_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('differentiators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_group_size', sa.Integer(), nullable=True),
    sa.Column('typical_group_size', sa.Integer(), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('indicative_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("name IS NULL OR (jsonb_exists(name, 'en') AND length(trim(name ->> 'en')) > 0)", name=op.f('ck_service_tiers_name_has_english')),
    sa.CheckConstraint('max_group_size >= 1', name=op.f('ck_service_tiers_group_size_positive')),
    sa.ForeignKeyConstraint(['journey_id'], ['yatra.journeys.id'], name=op.f('fk_service_tiers_journey_id_journeys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_tiers')),
    sa.UniqueConstraint('journey_id', 'slug', name=op.f('uq_service_tiers_journey_id')),
    schema='yatra'
    )
    op.create_table('stays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kind', sa.Enum('homestay', 'guesthouse', 'hotel', 'lodge', 'camp', 'ashram_or_dharamshala', name='stay_kind', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('host_name', sa.String(length=200), nullable=True),
    sa.Column('household_story', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('village', sa.String(length=160), nullable=True),
    sa.Column('shares_family_meals', sa.Boolean(), nullable=True),
    sa.Column('rooms_available', sa.Integer(), nullable=True),
    sa.Column('typical_occupancy', sa.Integer(), nullable=True),
    sa.Column('has_running_hot_water', sa.Boolean(), nullable=True),
    sa.Column('has_heating', sa.Boolean(), nullable=True),
    sa.Column('has_mobile_network', sa.Boolean(), nullable=True),
    sa.Column('is_shared_bathroom', sa.Boolean(), nullable=True),
    sa.Column('limitations_note', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_verified_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("name IS NULL OR (jsonb_exists(name, 'en') AND length(trim(name ->> 'en')) > 0)", name=op.f('ck_stays_name_has_english')),
    sa.ForeignKeyConstraint(['destination_id'], ['yatra.destinations.id'], name=op.f('fk_stays_destination_id_destinations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stays')),
    sa.UniqueConstraint('slug', name=op.f('uq_stays_slug')),
    schema='yatra'
    )
    op.create_table('departures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('service_tier_id', sa.Integer(), nullable=False),
    sa.Column('itinerary_version_id', sa.Integer(), nullable=True),
    sa.Column('operating_partner_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('gateway', sa.String(length=120), nullable=True),
    sa.Column('state', sa.Enum('draft', 'feasibility_review', 'proposed', 'waitlist_open', 'conditional_reservation', 'open_for_booking', 'minimum_group_pending', 'confirmed', 'preparation', 'ready_to_depart', 'in_progress', 'completed', 'suspended', 'rescheduled', 'cancelled', name='departure_state', schema='yatra', inherit_schema=True), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('capacity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reserved_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('state_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state_changed_by', sa.String(length=120), nullable=True),
    sa.Column('state_change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("state not in ('open_for_booking','minimum_group_pending','confirmed','preparation','ready_to_depart','in_progress') or operating_partner_id is not null", name=op.f('ck_departures_sellable_departure_needs_operator')),
    sa.CheckConstraint('capacity >= 0', name=op.f('ck_departures_capacity_non_negative')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_departures_dates_ordered')),
    sa.CheckConstraint('reserved_count <= capacity', name=op.f('ck_departures_reserved_within_capacity')),
    sa.CheckConstraint('reserved_count >= 0', name=op.f('ck_departures_reserved_non_negative')),
    sa.ForeignKeyConstraint(['itinerary_version_id'], ['yatra.itinerary_versions.id'], name=op.f('fk_departures_itinerary_version_id_itinerary_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journey_id'], ['yatra.journeys.id'], name=op.f('fk_departures_journey_id_journeys'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operating_partner_id'], ['yatra.operating_partners.id'], name=op.f('fk_departures_operating_partner_id_operating_partners'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_tier_id'], ['yatra.service_tiers.id'], name=op.f('fk_departures_service_tier_id_service_tiers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departures')),
    sa.UniqueConstraint('journey_id', 'service_tier_id', 'start_date', name=op.f('uq_departures_journey_id')),
    schema='yatra'
    )
    op.create_index('ix_departures_state_start', 'departures', ['state', 'start_date'], unique=False, schema='yatra')
    op.create_table('itinerary_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('itinerary_version_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('origin_destination_id', sa.Integer(), nullable=True),
    sa.Column('arrival_destination_id', sa.Integer(), nullable=True),
    sa.Column('stay_id', sa.Integer(), nullable=True),
    sa.Column('travel_note', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('altitude_note', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_route_dependent', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("title IS NULL OR (jsonb_exists(title, 'en') AND length(trim(title ->> 'en')) > 0)", name=op.f('ck_itinerary_stages_title_has_english')),
    sa.ForeignKeyConstraint(['arrival_destination_id'], ['yatra.destinations.id'], name=op.f('fk_itinerary_stages_arrival_destination_id_destinations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['itinerary_version_id'], ['yatra.itinerary_versions.id'], name=op.f('fk_itinerary_stages_itinerary_version_id_itinerary_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_destination_id'], ['yatra.destinations.id'], name=op.f('fk_itinerary_stages_origin_destination_id_destinations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stay_id'], ['yatra.stays.id'], name=op.f('fk_itinerary_stages_stay_id_stays'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itinerary_stages')),
    sa.UniqueConstraint('itinerary_version_id', 'day_number', name=op.f('uq_itinerary_stages_itinerary_version_id')),
    schema='yatra'
    )
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('alt_text', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance', sa.Enum('original', 'supplier_provided', 'licensed_editorial', 'illustrative', 'ai_generated', name='media_provenance', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('represents_actual_conditions', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('credit', sa.String(length=200), nullable=True),
    sa.Column('captured_on', sa.String(length=32), nullable=True),
    sa.Column('stay_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('journey_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("alt_text IS NULL OR (jsonb_exists(alt_text, 'en') AND length(trim(alt_text ->> 'en')) > 0)", name=op.f('ck_media_assets_alt_text_has_english')),
    sa.CheckConstraint("not (represents_actual_conditions and provenance in ('illustrative', 'ai_generated'))", name=op.f('ck_media_assets_illustrative_media_cannot_claim_reality')),
    sa.ForeignKeyConstraint(['destination_id'], ['yatra.destinations.id'], name=op.f('fk_media_assets_destination_id_destinations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journey_id'], ['yatra.journeys.id'], name=op.f('fk_media_assets_journey_id_journeys'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stay_id'], ['yatra.stays.id'], name=op.f('fk_media_assets_stay_id_stays'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    schema='yatra'
    )
    op.create_table('status_updates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_segment_id', sa.Integer(), nullable=False),
    sa.Column('access', sa.Enum('open', 'limited', 'permit_pending', 'suspended', 'closed', 'not_in_season', 'unverified', name='route_access', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('stage', sa.Enum('field_input', 'unverified_note', 'reviewed', 'published', 'superseded', name='status_publication_stage', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('source', sa.Enum('official_notice', 'district_or_tourism', 'operating_partner', 'field_coordinator', 'supplier_observation', name='status_source_type', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('verified_by', sa.String(length=120), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_verification_due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("stage <> 'published' or (verified_by is not null and summary is not null and length(trim(summary ->> 'en')) > 0)", name=op.f('ck_status_updates_published_status_needs_verifier_and_summary')),
    sa.CheckConstraint('next_verification_due > verified_at', name=op.f('ck_status_updates_verification_window_is_forward')),
    sa.ForeignKeyConstraint(['route_segment_id'], ['yatra.route_segments.id'], name=op.f('fk_status_updates_route_segment_id_route_segments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_updates')),
    schema='yatra'
    )
    op.create_index('ix_status_updates_segment_verified', 'status_updates', ['route_segment_id', 'verified_at'], unique=False, schema='yatra')
    op.create_table('departure_state_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('departure_id', sa.Integer(), nullable=False),
    sa.Column('previous_state', sa.Enum('draft', 'feasibility_review', 'proposed', 'waitlist_open', 'conditional_reservation', 'open_for_booking', 'minimum_group_pending', 'confirmed', 'preparation', 'ready_to_depart', 'in_progress', 'completed', 'suspended', 'rescheduled', 'cancelled', name='departure_state', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('new_state', sa.Enum('draft', 'feasibility_review', 'proposed', 'waitlist_open', 'conditional_reservation', 'open_for_booking', 'minimum_group_pending', 'confirmed', 'preparation', 'ready_to_depart', 'in_progress', 'completed', 'suspended', 'rescheduled', 'cancelled', name='departure_state', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(trim(actor)) > 0', name=op.f('ck_departure_state_changes_actor_present')),
    sa.CheckConstraint('length(trim(reason)) > 0', name=op.f('ck_departure_state_changes_reason_present')),
    sa.ForeignKeyConstraint(['departure_id'], ['yatra.departures.id'], name=op.f('fk_departure_state_changes_departure_id_departures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departure_state_changes')),
    schema='yatra'
    )
    op.create_index('ix_departure_state_changes_departure', 'departure_state_changes', ['departure_id', 'created_at'], unique=False, schema='yatra')
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('preferred_language', sa.String(length=8), server_default=sa.text("'en'"), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('origin_city', sa.String(length=120), nullable=True),
    sa.Column('raahi_user_id', sa.Integer(), nullable=True),
    sa.Column('journey_id', sa.Integer(), nullable=True),
    sa.Column('departure_id', sa.Integer(), nullable=True),
    sa.Column('preferred_date_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_date_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('group_size', sa.Integer(), nullable=True),
    sa.Column('is_senior_inclusive', sa.Boolean(), nullable=True),
    sa.Column('tier_preference', sa.String(length=60), nullable=True),
    sa.Column('primary_concern', sa.Text(), nullable=True),
    sa.Column('first_touch_source', sa.String(length=120), nullable=True),
    sa.Column('latest_touch_source', sa.String(length=120), nullable=True),
    sa.Column('campaign', sa.String(length=160), nullable=True),
    sa.Column('landing_page', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('stage', sa.Enum('new', 'contacted', 'qualified', 'consultation_scheduled', 'proposal_shared', 'reservation_invited', 'reserved', 'confirmed', 'nurture', 'lost', name='lead_stage', schema='yatra', inherit_schema=True), server_default=sa.text("'new'"), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('next_action_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loss_reason', sa.String(length=120), nullable=True),
    sa.Column('nurture_topic', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("stage <> 'lost' or loss_reason is not null", name=op.f('ck_leads_lost_lead_needs_a_reason')),
    sa.CheckConstraint('phone is not null or email is not null', name=op.f('ck_leads_lead_needs_a_contact_method')),
    sa.ForeignKeyConstraint(['departure_id'], ['yatra.departures.id'], name=op.f('fk_leads_departure_id_departures'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journey_id'], ['yatra.journeys.id'], name=op.f('fk_leads_journey_id_journeys'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raahi_user_id'], ['public.users.id'], name=op.f('fk_leads_raahi_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    schema='yatra'
    )
    op.create_index('ix_leads_next_action_due', 'leads', ['next_action_due_at'], unique=False, schema='yatra')
    op.create_index('ix_leads_stage_owner', 'leads', ['stage', 'owner'], unique=False, schema='yatra')
    op.create_index(op.f('ix_yatra_leads_raahi_user_id'), 'leads', ['raahi_user_id'], unique=False, schema='yatra')
    op.create_table('lead_consents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('essential_trip', 'route_status_alerts', 'promotional', name='consent_purpose', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'email', 'sms', 'phone', name='consent_channel', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('withdrawn_at is null or withdrawn_at >= granted_at', name=op.f('ck_lead_consents_withdrawal_follows_grant')),
    sa.ForeignKeyConstraint(['lead_id'], ['yatra.leads.id'], name=op.f('fk_lead_consents_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_consents')),
    schema='yatra'
    )
    op.create_index('ix_lead_consents_lead_purpose', 'lead_consents', ['lead_id', 'purpose'], unique=False, schema='yatra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lead_consents_lead_purpose', table_name='lead_consents', schema='yatra')
    op.drop_table('lead_consents', schema='yatra')
    op.drop_index(op.f('ix_yatra_leads_raahi_user_id'), table_name='leads', schema='yatra')
    op.drop_index('ix_leads_stage_owner', table_name='leads', schema='yatra')
    op.drop_index('ix_leads_next_action_due', table_name='leads', schema='yatra')
    op.drop_table('leads', schema='yatra')
    op.drop_index('ix_departure_state_changes_departure', table_name='departure_state_changes', schema='yatra')
    op.drop_table('departure_state_changes', schema='yatra')
    op.drop_index('ix_status_updates_segment_verified', table_name='status_updates', schema='yatra')
    op.drop_table('status_updates', schema='yatra')
    op.drop_table('media_assets', schema='yatra')
    op.drop_table('itinerary_stages', schema='yatra')
    op.drop_index('ix_departures_state_start', table_name='departures', schema='yatra')
    op.drop_table('departures', schema='yatra')
    op.drop_table('stays', schema='yatra')
    op.drop_table('service_tiers', schema='yatra')
    op.drop_table('route_segments', schema='yatra')
    op.drop_table('itinerary_versions', schema='yatra')
    op.drop_table('operating_partners', schema='yatra')
    op.drop_table('journeys', schema='yatra')
    op.drop_table('destinations', schema='yatra')
    # ### end Alembic commands ###

    # Alembic does not drop enum types it created implicitly, which leaves a re-run
    # migration hitting "type already exists". Schema-qualified so this can never
    # reach Raahi's types in public.
    for enum_name in (
        "stay_kind",
        "journey_family",
        "media_provenance",
        "route_access",
        "status_publication_stage",
        "status_source_type",
        "departure_state",
        "lead_stage",
        "consent_purpose",
        "consent_channel",
    ):
        op.execute(f'DROP TYPE IF EXISTS yatra."{enum_name}"')
