"""destination altitude provenance

Revision ID: d03cf559ea26
Revises: aef737d73349
Create Date: 2026-08-13 20:12:28.044485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03cf559ea26'
down_revision: Union[str, Sequence[str], None] = 'aef737d73349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('altitude_source', sa.String(length=300), nullable=True), schema='yatra')
    op.add_column('destinations', sa.Column('altitude_recorded_by', sa.String(length=120), nullable=True), schema='yatra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'altitude_recorded_by', schema='yatra')
    op.drop_column('destinations', 'altitude_source', schema='yatra')
    # ### end Alembic commands ###
