"""traveller tokens can open a reservation

Revision ID: ee13ff07d12c
Revises: 87e61cf3e55c
Create Date: 2026-08-11 09:47:57.741497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee13ff07d12c'
down_revision: Union[str, Sequence[str], None] = '87e61cf3e55c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traveller_access_tokens', sa.Column('reservation_id', sa.Integer(), nullable=True), schema='yatra')
    op.alter_column('traveller_access_tokens', 'lead_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='yatra')
    op.create_index('ix_traveller_access_tokens_reservation', 'traveller_access_tokens', ['reservation_id'], unique=False, schema='yatra')
    op.create_check_constraint(op.f('ck_traveller_access_tokens_token_points_at_something'), 'traveller_access_tokens', 'lead_id is not null or reservation_id is not null', schema='yatra')
    # ### end Alembic commands ###

    # By hand again: the include_object filter in alembic/env.py drops foreign keys
    # on add_column. See the note in 87e61cf3e55c. Autogenerate will not warn.
    op.create_foreign_key(
        op.f("fk_traveller_access_tokens_reservation_id_reservations"),
        "traveller_access_tokens",
        "reservations",
        ["reservation_id"],
        ["id"],
        source_schema="yatra",
        referent_schema="yatra",
        ondelete="CASCADE",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_traveller_access_tokens_token_points_at_something'), 'traveller_access_tokens', schema='yatra', type_='check')
    op.drop_index('ix_traveller_access_tokens_reservation', table_name='traveller_access_tokens', schema='yatra')
    op.alter_column('traveller_access_tokens', 'lead_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='yatra')
    op.drop_constraint(
        op.f("fk_traveller_access_tokens_reservation_id_reservations"),
        "traveller_access_tokens",
        schema="yatra",
        type_="foreignkey",
    )
    op.drop_column('traveller_access_tokens', 'reservation_id', schema='yatra')
    # ### end Alembic commands ###
