"""advocacy, family sharing, specialised enquiries, check-ins

Revision ID: f62c31b08c3d
Revises: 0c5ce0bcbb67
Create Date: 2026-08-12 16:26:06.521169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

#: `op.add_column` does NOT create a Postgres enum type — the CREATE TYPE hook that
#: SQLAlchemy attaches fires on table creation, not on ALTER TABLE ADD COLUMN. Left
#: to autogenerate, the statement below fails with "type enquiry_kind does not
#: exist". So the type is created explicitly first and the column declares
#: create_type=False.
enquiry_kind = postgresql.ENUM(
    "standard",
    "private_or_international",
    "b2b_ground_handling",
    name="enquiry_kind",
    schema="yatra",
    create_type=False,
)


# revision identifiers, used by Alembic.
revision: str = 'f62c31b08c3d'
down_revision: Union[str, Sequence[str], None] = '0c5ce0bcbb67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departure_check_ins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('departure_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('posted_by', sa.String(length=120), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_shareable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(trim(note)) > 0', name=op.f('ck_departure_check_ins_check_in_note_present')),
    sa.CheckConstraint('length(trim(posted_by)) > 0', name=op.f('ck_departure_check_ins_check_in_author_present')),
    sa.ForeignKeyConstraint(['departure_id'], ['yatra.departures.id'], name=op.f('fk_departure_check_ins_departure_id_departures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departure_check_ins')),
    schema='yatra'
    )
    op.create_index('ix_departure_check_ins_departure', 'departure_check_ins', ['departure_id', 'occurred_at'], unique=False, schema='yatra')
    op.create_table('enquiry_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('date_flexibility', sa.Text(), nullable=True),
    sa.Column('group_size_min', sa.Integer(), nullable=True),
    sa.Column('group_size_max', sa.Integer(), nullable=True),
    sa.Column('age_range', sa.String(length=120), nullable=True),
    sa.Column('experience_preference', sa.Text(), nullable=True),
    sa.Column('gateway_needs', sa.Text(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('time_zone', sa.String(length=64), nullable=True),
    sa.Column('consultation_window', sa.String(length=160), nullable=True),
    sa.Column('consultation_channel', sa.String(length=40), nullable=True),
    sa.Column('accessibility_needs', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('company_role', sa.String(length=120), nullable=True),
    sa.Column('company_website', sa.String(length=300), nullable=True),
    sa.Column('company_registration', sa.String(length=80), nullable=True),
    sa.Column('services_needed', sa.Text(), nullable=True),
    sa.Column('volume_estimate', sa.String(length=200), nullable=True),
    sa.Column('season_of_interest', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('group_size_max is null or group_size_min is null or group_size_max >= group_size_min', name=op.f('ck_enquiry_details_group_size_ordered')),
    sa.ForeignKeyConstraint(['lead_id'], ['yatra.leads.id'], name=op.f('fk_enquiry_details_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enquiry_details')),
    sa.UniqueConstraint('lead_id', name='one_detail_per_lead'),
    schema='yatra'
    )
    op.create_index('ix_enquiry_details_timezone', 'enquiry_details', ['time_zone'], unique=False, schema='yatra')
    op.create_table('family_shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shows_check_ins', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(trim(label)) > 0', name=op.f('ck_family_shares_share_label_present')),
    sa.CheckConstraint('revoked_at is null or revoked_reason is not null', name=op.f('ck_family_shares_revocation_needs_a_reason')),
    sa.ForeignKeyConstraint(['reservation_id'], ['yatra.reservations.id'], name=op.f('fk_family_shares_reservation_id_reservations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_shares')),
    sa.UniqueConstraint('token', name=op.f('uq_family_shares_token')),
    schema='yatra'
    )
    op.create_index('ix_family_shares_reservation', 'family_shares', ['reservation_id'], unique=False, schema='yatra')
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('referrer_name', sa.String(length=200), nullable=True),
    sa.Column('terms_version', sa.String(length=40), nullable=False),
    sa.Column('benefit', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(trim(code)) >= 4', name=op.f('ck_referrals_referral_code_present')),
    sa.ForeignKeyConstraint(['reservation_id'], ['yatra.reservations.id'], name=op.f('fk_referrals_reservation_id_reservations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals')),
    sa.UniqueConstraint('code', name='referral_code_unique'),
    schema='yatra'
    )
    op.create_index('ix_referrals_reservation', 'referrals', ['reservation_id'], unique=False, schema='yatra')
    op.create_table('trip_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.String(length=200), nullable=True),
    sa.Column('sales_promise_accuracy', sa.SmallInteger(), nullable=True),
    sa.Column('preparation', sa.SmallInteger(), nullable=True),
    sa.Column('pickup_and_transport', sa.SmallInteger(), nullable=True),
    sa.Column('accommodation', sa.SmallInteger(), nullable=True),
    sa.Column('coordinator_support', sa.SmallInteger(), nullable=True),
    sa.Column('route_communication', sa.SmallInteger(), nullable=True),
    sa.Column('spiritual_and_cultural', sa.SmallInteger(), nullable=True),
    sa.Column('recommend_score', sa.SmallInteger(), nullable=True),
    sa.Column('what_went_well', sa.Text(), nullable=True),
    sa.Column('what_went_wrong', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('accommodation is null or accommodation between 1 and 5', name=op.f('ck_trip_feedback_accommodation_range')),
    sa.CheckConstraint('coordinator_support is null or coordinator_support between 1 and 5', name=op.f('ck_trip_feedback_coordinator_support_range')),
    sa.CheckConstraint('pickup_and_transport is null or pickup_and_transport between 1 and 5', name=op.f('ck_trip_feedback_pickup_and_transport_range')),
    sa.CheckConstraint('preparation is null or preparation between 1 and 5', name=op.f('ck_trip_feedback_preparation_range')),
    sa.CheckConstraint('recommend_score is null or recommend_score between 0 and 10', name=op.f('ck_trip_feedback_recommend_score_range')),
    sa.CheckConstraint('route_communication is null or route_communication between 1 and 5', name=op.f('ck_trip_feedback_route_communication_range')),
    sa.CheckConstraint('sales_promise_accuracy is null or sales_promise_accuracy between 1 and 5', name=op.f('ck_trip_feedback_sales_promise_accuracy_range')),
    sa.CheckConstraint('spiritual_and_cultural is null or spiritual_and_cultural between 1 and 5', name=op.f('ck_trip_feedback_spiritual_and_cultural_range')),
    sa.ForeignKeyConstraint(['reservation_id'], ['yatra.reservations.id'], name=op.f('fk_trip_feedback_reservation_id_reservations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_feedback')),
    sa.UniqueConstraint('reservation_id', name='one_feedback_per_reservation'),
    sa.UniqueConstraint('token', name=op.f('uq_trip_feedback_token')),
    schema='yatra'
    )
    op.create_index('ix_trip_feedback_submitted', 'trip_feedback', ['submitted_at'], unique=False, schema='yatra')
    op.create_table('family_share_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('coarse_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent_family', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['share_id'], ['yatra.family_shares.id'], name=op.f('fk_family_share_views_share_id_family_shares'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_share_views')),
    schema='yatra'
    )
    op.create_index('ix_family_share_views_share', 'family_share_views', ['share_id', 'created_at'], unique=False, schema='yatra')
    op.create_table('feedback_complaints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=60), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('resolution_state', sa.Enum('open', 'resolved', 'acknowledged', name='complaint_resolution_state', schema='yatra', inherit_schema=True), server_default=sa.text("'open'"), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=120), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("resolution_state = 'open' or (resolved_by is not null and length(trim(coalesce(resolution_note,''))) > 0)", name=op.f('ck_feedback_complaints_resolution_needs_an_owner_and_a_note')),
    sa.ForeignKeyConstraint(['feedback_id'], ['yatra.trip_feedback.id'], name=op.f('fk_feedback_complaints_feedback_id_trip_feedback'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback_complaints')),
    schema='yatra'
    )
    op.create_index('ix_feedback_complaints_state', 'feedback_complaints', ['resolution_state'], unique=False, schema='yatra')
    op.create_table('referral_attributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=True),
    sa.Column('raw_code', sa.String(length=40), nullable=False),
    sa.Column('matched', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['yatra.leads.id'], name=op.f('fk_referral_attributions_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referral_id'], ['yatra.referrals.id'], name=op.f('fk_referral_attributions_referral_id_referrals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_attributions')),
    sa.UniqueConstraint('lead_id', name='one_attribution_per_lead'),
    schema='yatra'
    )
    op.create_index('ix_referral_attributions_referral', 'referral_attributions', ['referral_id'], unique=False, schema='yatra')
    op.create_table('review_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('google', 'tripadvisor', 'own_site', name='review_platform', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('asked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('asked_by', sa.String(length=120), nullable=True),
    sa.Column('left_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('may_publish_written_review', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('may_publish_images', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('may_publish_story', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('permission_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['yatra.trip_feedback.id'], name=op.f('fk_review_requests_feedback_id_trip_feedback'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_requests')),
    sa.UniqueConstraint('feedback_id', 'platform', name='one_ask_per_platform'),
    schema='yatra'
    )
    op.create_index('ix_review_requests_asked', 'review_requests', ['asked_at'], unique=False, schema='yatra')
    enquiry_kind.create(op.get_bind(), checkfirst=True)
    # NOT NULL with a server default: existing leads all became `standard`, which is
    # what they were. Backfill is implicit and correct rather than a separate step.
    op.add_column(
        'leads',
        sa.Column('enquiry_kind', enquiry_kind, server_default=sa.text("'standard'"), nullable=False),
        schema='yatra',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'enquiry_kind', schema='yatra')
    enquiry_kind.drop(op.get_bind(), checkfirst=True)
    op.drop_index('ix_review_requests_asked', table_name='review_requests', schema='yatra')
    op.drop_table('review_requests', schema='yatra')
    op.drop_index('ix_referral_attributions_referral', table_name='referral_attributions', schema='yatra')
    op.drop_table('referral_attributions', schema='yatra')
    op.drop_index('ix_feedback_complaints_state', table_name='feedback_complaints', schema='yatra')
    op.drop_table('feedback_complaints', schema='yatra')
    op.drop_index('ix_family_share_views_share', table_name='family_share_views', schema='yatra')
    op.drop_table('family_share_views', schema='yatra')
    op.drop_index('ix_trip_feedback_submitted', table_name='trip_feedback', schema='yatra')
    op.drop_table('trip_feedback', schema='yatra')
    op.drop_index('ix_referrals_reservation', table_name='referrals', schema='yatra')
    op.drop_table('referrals', schema='yatra')
    op.drop_index('ix_family_shares_reservation', table_name='family_shares', schema='yatra')
    op.drop_table('family_shares', schema='yatra')
    op.drop_index('ix_enquiry_details_timezone', table_name='enquiry_details', schema='yatra')
    op.drop_table('enquiry_details', schema='yatra')
    op.drop_index('ix_departure_check_ins_departure', table_name='departure_check_ins', schema='yatra')
    op.drop_table('departure_check_ins', schema='yatra')
    # ### end Alembic commands ###
