"""suppliers, payables, rooming and incidents

Revision ID: fa0ff3a1785b
Revises: 01f50c3d378b
Create Date: 2026-08-11 18:23:34.586944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fa0ff3a1785b'
down_revision: Union[str, Sequence[str], None] = '01f50c3d378b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('transport', 'guide', 'porter', 'stay', 'permit_agent', 'other', name='supplier_kind', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('village', sa.String(length=160), nullable=True),
    sa.Column('stay_id', sa.Integer(), nullable=True),
    sa.Column('reliability_note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_suppliers_supplier_name_present')),
    sa.ForeignKeyConstraint(['stay_id'], ['yatra.stays.id'], name=op.f('fk_suppliers_stay_id_stays'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    schema='yatra'
    )
    op.create_index('ix_suppliers_kind', 'suppliers', ['kind'], unique=False, schema='yatra')
    op.create_table('supplier_bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('departure_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('state', sa.Enum('enquired', 'confirmed', 'delivered', 'cancelled', name='supplier_booking_state', schema='yatra', inherit_schema=True), server_default=sa.text("'enquired'"), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('agreed_cost', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('confirmed_by', sa.String(length=120), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("state <> 'cancelled' or length(trim(coalesce(cancellation_reason,''))) > 0", name=op.f('ck_supplier_bookings_supplier_cancellation_needs_reason')),
    sa.CheckConstraint('agreed_cost >= 0', name=op.f('ck_supplier_bookings_agreed_cost_non_negative')),
    sa.ForeignKeyConstraint(['departure_id'], ['yatra.departures.id'], name=op.f('fk_supplier_bookings_departure_id_departures'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['yatra.suppliers.id'], name=op.f('fk_supplier_bookings_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_bookings')),
    schema='yatra'
    )
    op.create_index('ix_supplier_bookings_departure', 'supplier_bookings', ['departure_id', 'state'], unique=False, schema='yatra')
    op.create_table('supplier_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_booking_id', sa.Integer(), nullable=False),
    # `payment_direction` and `payment_method` already exist: they were created for
    # the customer ledger, and supplier_payments deliberately reuses them so the two
    # sides of the business cannot drift apart. Autogenerate does not know that and
    # emits a second CREATE TYPE, which fails with DuplicateObject. `create_type=False`
    # references the existing type instead. Any future table reusing an enum needs the
    # same treatment.
    sa.Column('direction', postgresql.ENUM(name='payment_direction', schema='yatra', create_type=False), server_default=sa.text("'received'"), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('method', postgresql.ENUM(name='payment_method', schema='yatra', create_type=False), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_supplier_payments_supplier_amount_positive')),
    sa.CheckConstraint('length(trim(recorded_by)) > 0', name=op.f('ck_supplier_payments_supplier_recorder_present')),
    sa.ForeignKeyConstraint(['supplier_booking_id'], ['yatra.supplier_bookings.id'], name=op.f('fk_supplier_payments_supplier_booking_id_supplier_bookings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_payments')),
    schema='yatra'
    )
    op.create_index('ix_supplier_payments_booking', 'supplier_payments', ['supplier_booking_id', 'paid_at'], unique=False, schema='yatra')
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('departure_id', sa.Integer(), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('reservation_traveller_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('near_miss', 'minor', 'significant', 'serious', 'critical', name='incident_severity', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('category', sa.Enum('health_altitude', 'road_vehicle', 'weather_route', 'accommodation', 'permit_checkpost', 'conduct', 'supplier_failure', 'other', name='incident_category', schema='yatra', inherit_schema=True), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed', sa.Text(), nullable=False),
    sa.Column('immediate_action', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('reported_by', sa.String(length=120), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=120), nullable=True),
    sa.Column('travellers_informed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("resolved_at is null or length(trim(coalesce(outcome,''))) > 0", name=op.f('ck_incidents_resolved_incident_needs_outcome')),
    sa.CheckConstraint('length(trim(observed)) > 0', name=op.f('ck_incidents_incident_observed_present')),
    sa.CheckConstraint('length(trim(reported_by)) > 0', name=op.f('ck_incidents_incident_reporter_present')),
    sa.ForeignKeyConstraint(['departure_id'], ['yatra.departures.id'], name=op.f('fk_incidents_departure_id_departures'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['yatra.reservations.id'], name=op.f('fk_incidents_reservation_id_reservations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_traveller_id'], ['yatra.reservation_travellers.id'], name=op.f('fk_incidents_reservation_traveller_id_reservation_travellers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['yatra.suppliers.id'], name=op.f('fk_incidents_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents')),
    schema='yatra'
    )
    op.create_index('ix_incidents_departure', 'incidents', ['departure_id', 'occurred_at'], unique=False, schema='yatra')
    op.create_index('ix_incidents_open', 'incidents', ['resolved_at'], unique=False, schema='yatra')
    op.create_table('rooming_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('departure_id', sa.Integer(), nullable=False),
    sa.Column('reservation_traveller_id', sa.Integer(), nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('night', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('assigned_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['departure_id'], ['yatra.departures.id'], name=op.f('fk_rooming_assignments_departure_id_departures'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_traveller_id'], ['yatra.reservation_travellers.id'], name=op.f('fk_rooming_assignments_reservation_traveller_id_reservation_travellers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stay_id'], ['yatra.stays.id'], name=op.f('fk_rooming_assignments_stay_id_stays'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooming_assignments')),
    sa.UniqueConstraint('reservation_traveller_id', 'night', name='one_bed_per_person_per_night'),
    schema='yatra'
    )
    op.create_index('ix_rooming_departure_night', 'rooming_assignments', ['departure_id', 'night'], unique=False, schema='yatra')
    op.create_index('ix_rooming_stay_night', 'rooming_assignments', ['stay_id', 'night'], unique=False, schema='yatra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rooming_stay_night', table_name='rooming_assignments', schema='yatra')
    op.drop_index('ix_rooming_departure_night', table_name='rooming_assignments', schema='yatra')
    op.drop_table('rooming_assignments', schema='yatra')
    op.drop_index('ix_incidents_open', table_name='incidents', schema='yatra')
    op.drop_index('ix_incidents_departure', table_name='incidents', schema='yatra')
    op.drop_table('incidents', schema='yatra')
    op.drop_index('ix_supplier_payments_booking', table_name='supplier_payments', schema='yatra')
    op.drop_table('supplier_payments', schema='yatra')
    op.drop_index('ix_supplier_bookings_departure', table_name='supplier_bookings', schema='yatra')
    op.drop_table('supplier_bookings', schema='yatra')
    op.drop_index('ix_suppliers_kind', table_name='suppliers', schema='yatra')
    op.drop_table('suppliers', schema='yatra')
    # ### end Alembic commands ###
