"""Regenerate `docs/WHATSAPP-TEMPLATES.md` from the template registry.

    uv run python scripts/generate_template_docs.py

The generated file is what somebody pastes into Meta's template manager. Generating
it rather than writing it by hand is the whole point: if the submitted wording and
the wording in `domain/templates.py` ever diverge, every send fails with a
mismatched-template error, and the error does not say which of the two is wrong.

Run this and commit the result whenever a template body changes.
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from api.domain.status import Access  # noqa: E402
from api.domain.subscriptions import Change  # noqa: E402
from api.domain.templates import (  # noqa: E402
    ALL_TEMPLATES,
    submission_problems,
    template_for,
)

OUTPUT = Path(__file__).resolve().parents[3] / "docs" / "WHATSAPP-TEMPLATES.md"

PREAMBLE = """# WhatsApp / SMS message templates

**Generated by `apps/api/scripts/generate_template_docs.py` from
`apps/api/src/api/domain/templates.py`. Do not edit by hand** — edit the registry and
re-run the script. If the text submitted to Meta and the text the code sends ever
drift apart, every send fails with a mismatched-template error that does not say
which of the two is wrong.

## Before you submit anything

1. **Do not register +91 83408 58764 on the Cloud API.** Registering a number on the
   WhatsApp Business Platform removes it from the ordinary WhatsApp app. That number
   is the one a person answers (decision D24); the API needs a second one.
2. Category is **Utility** for all four. They follow from a request the recipient
   made about a specific route. Submitting them as Marketing costs more and is
   untrue, and Meta re-categorises templates that read as promotional — a
   re-categorised template can put the whole number under review.
3. Language: submit **English** first. Hindi is a separate translation of the *same*
   template name, so the parameter order has to match position for position.
4. There is **no URL button yet**, deliberately. A button URL is part of the approved
   template and cannot change without re-approval, so adding one before the domain is
   settled (O7) means resubmitting all four the day it lands.
5. `sending_enabled` stays false in the API regardless. Approval is necessary, not
   sufficient — a provider and a token still have to exist (O9).

## Templates
"""

SAMPLES = [
    ("closure", Access.OPEN, Access.CLOSED, "Landslide near Gunji, both lanes blocked."),
    ("reopening", Access.CLOSED, Access.OPEN, "Cleared this morning, single lane."),
    ("first status", None, Access.OPEN, "Verified on the ground by our coordinator."),
    ("ordinary change", Access.OPEN, Access.LIMITED, "Single lane past the slide."),
]


def build() -> str:
    lines = [PREAMBLE]

    for template in ALL_TEMPLATES:
        problems = submission_problems(template)
        lines += [
            f"### `{template.name}`",
            "",
            f"- **Category:** {template.category.value.title()}",
            f"- **Variables:** {template.parameter_count}",
            "- **Submittable:** "
            + ("yes" if not problems else "NO — " + "; ".join(problems)),
            "",
            "**Body**",
            "",
            "```",
            template.body,
            "```",
            "",
        ]
        if template.footer:
            lines += ["**Footer**", "", "```", template.footer, "```", ""]

    lines += [
        "## Sample values for the review form",
        "",
        "Meta requires an example for every variable. These are the shapes the code",
        "actually produces — a reviewer who sees a plausible example approves faster,",
        "and an example that does not match what you really send is grounds for",
        "suspension later.",
        "",
    ]

    for label, previous, new, summary in SAMPLES:
        change = Change(
            segment_slug="gunji-nabhidhang",
            segment_name="Gunji to Nabhidhang",
            previous_access=previous,
            new_access=new,
            published_at=datetime(2027, 5, 20, tzinfo=timezone.utc),
            summary=summary,
        )
        message = template_for(change)
        lines += [f"**{label} → `{message.name}`**", ""]
        lines += [
            f"- `{{{{{i}}}}}` — {value}"
            for i, value in enumerate(message.parameters, 1)
        ]
        lines += ["", "Renders as:", "", "> " + message.rendered, ""]

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    OUTPUT.write_text(build())
    print(f"Wrote {OUTPUT}")
